### PR TITLE
[VoiceMessages] Add Support for Android < 10

### PR DESCRIPTION
**Pull request by AbdullahM0hamed**

### CODE REVIEW

**Comment by mantikafasi** [comment]
does discord even support aac extension, and even if it does offically they only use opus afaik so idk

**Comment by AbdullahM0hamed** [comment]
> does discord even support aac extension, and even if it does offically they only use opus afaik so idk

Not sure, but it definitely does seem better as a pre-10 user to be able to send as aac instead of having to go through a voice recorder app and share it to discord

**Comment by mantikafasi** [comment]
probably but I dont want to send weird requests to discord either

**Comment by ArjixWasTaken** [comment]
just bundle ffmpeg :trollface:

**Pull request merged**
