### PR TITLE
delete plugin

### PR DESCRIPTION
**Pull request by DiamondMiner88**
you will merge this

### CODE REVIEW

**Comment by mantikafasi** [comment]
Never

**Review by Vendicated — COMMENTED** [review]
MERGE NOW

**Comment by DiamondMiner88** [comment]
MERGE

**Comment by mantikafasi** [comment]
NEVER

**Comment by Vendicated** [comment]
can we get this merged

**Comment by DiamondMiner88** [comment]
please

**Comment by mantikafasi** [comment]
no it cant

**Pull request closed without merging**
